language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t cryptic20/dos-app -f Dockerfile .

script:
  - docker run -e CI=true indreklasn/my-react-docker-app npm run test

after_success:
  - docker build -t cryptic20/dos-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push indreklasn/my-react-docker-app
