language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t cryptic20/dosfrontend -f Dockerfile.dev .

script:
  - docker run -e CI=true cryptic20/dosfrontend npm run test

after_success:
  - docker build -t cryptic20/dosfrontend .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cryptic20/dosfrontend
