version: '3.7'

services:
  dosfrontend:
    stdin_open: true
    container_name: dosfrontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
